### ISSUE TITLE
Varying tooltips for 2018/2020?

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#117]
Would this be an input file on BC Data Catalogue? Start out with a local `JSON` file?

**Comment by hangler** [comment]
For now, a local JSON file. There's an option to put it onto the data catalogue.

**Comment by karmour** [comment]
Confirmed that the tooltips appear differently for 2018 and 2020 as desired. Looks like the bullets used within the "Shortfall" tooltip are not rendering as desired, but this is a small issue.

**Comment by stephanieyurchak** [comment]
Could we change the bulleted list to a numbered list to make the rendering issue less noticeable? @karmour thoughts?

**Comment by karmour** [comment]
> Could we change the bulleted list to a numbered list to make the rendering issue less noticeable? @karmour thoughts?

I like it! :-)

**Comment by hangler** [comment]
I was able to manage the bullets, but if you'd like numbers I can do that too!
<img width="296" alt="Screen Shot 2021-04-14 at 9 49 26 PM" src="https://user-images.githubusercontent.com/3538990/114815572-4e8f2e80-9d6b-11eb-9f57-64a14d66412b.png">

**Comment by karmour** [comment]
The bullets look good with your fix!

**Comment by hangler** [comment]
I am seeing the bullets in the latest deployment.

**Comment by karmour** [comment]
Confirmed!
