### ISSUE TITLE
Historical data indicator for non-most-recent data

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#120]
A box at the top of the screen. Similar to Statistics Canada notification on historical data.

**Comment by hangler** [comment]
> Add a note above the charts on each page to say "Note: Now viewing historical data", but only display this note when not viewing the most current dataset

**Comment by karmour** [comment]
Confirmed when viewing the 2018 dataset. Have not tested with other non-current datasets, as no such final datasets exist and we are consuming published data in the app. Consider as complete.
