### ISSUE TITLE
Github actions

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#121]
Look into the automation of a build artifact.

**Comment by hangler** [comment]
@robinwn Looks like the action worked and prepared an artifact: https://github.com/bcgov/workforce-profile-tool/actions/runs/768043917 This is without the `homepage` in `package.json` being updated (right now it's pointing to my own Github Pages site). As we just discussed, please do tell me what you'd need next 😄

@karmour FYI.

**Comment by robinwn** [comment]
Looks good and working well for deploys - thanks @hangler
