### ISSUE TITLE
Progress chart: lag when hiding values

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#127]
> Brief lag in hiding of some values on charts when switching filters/years (e.g., Indicators of Progress - going from 2020 to 2018, or hiding one of the designated groups)

**Comment by hangler** [comment]
They don't disappear absolutely instantaneously, but they also don't linger nearly as long as they used to.

**Comment by karmour** [comment]
Confirmed on the Indicators of Progress tab - they now disappear quite quickly! I did notice that the other tabs still seem to have the longer delay when removing a designated group from the visual (e.g., hiding "Indigenous Peoples" from the visual). If it's relatively quick to extend the speediness from Indicators of Progress to the other tabs, that would be great.

**Comment by hangler** [comment]
This problem is surprisingly annoying to fix, as I will discuss with you tomorrow.
