### ISSUE TITLE
Leadership: Fix locked filters

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#129]
> Locked filters left to remove (2020 for Regular and Aux employees)

**Comment by hangler** [comment]
To be clear, do we want the filters to appear or not to appear?

**Comment by hangler** [comment]
We do want to show them. Working as expected.

**Comment by karmour** [comment]
Confirmed in Edge.

@stephanieyurchak can you test in Chrome?

**Comment by karmour** [comment]
Confirmed in Chrome as well.
