### ISSUE TITLE
Ministries: de-selecting designated group causes crash

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#131]
> De-selecting any designated group causes the tool to crash (this includes de-selecting the group before navigating to the Ministries tab)

**Comment by karmour** [comment]
Confirmed in Edge.
@stephanieyurchak can you confirm in Chrome?

**Comment by stephanieyurchak** [comment]
Confirmed in Chrome

**Comment by hangler** [comment]
Great.
