### ISSUE TITLE
Representation charts bugged

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#132]
> Issues with the chart not displaying correctly (e.g., Office of the Premier, Mental Health & Addictions) -- and afterwards, chart will not display for any other group until moving to a different tab first

**Comment by karmour** [comment]
Confirmed in Edge. 
@stephanieyurchak can you confirm in Chrome?

**Comment by stephanieyurchak** [comment]
No it is not fixed. If I look at office of the premier, and deselect Women and Visible Minority (the groups that have data) then the chart renders strangely and continues to be "broken" if I re-select those groups or select another ministry. I have to refresh the page to view the chart correctly again.

**Comment by karmour** [comment]
Interesting - it looks fine in Edge even with those parameters. (For once, the Microsoft browser is not the LCM! ;-) ) @hangler can you investigate?

**Comment by hangler** [comment]
@stephanieyurchak Can confirm this happens with 2018 data, though 2020 works. Will work on a fix.

**Comment by hangler** [comment]
@stephanieyurchak @karmour OK, so this is not ideal, but it looks like the charting library has a problem when all data values are zero. I have replaced the chart with a message. Hope this addresses the problem adequately...

<img width="883" alt="Screen Shot 2021-04-14 at 7 04 53 PM" src="https://user-images.githubusercontent.com/3538990/114803517-72934580-9d54-11eb-8e4f-5495851ac3e2.png">

**Comment by karmour** [comment]
I'm ok with this solution! Moving to Final Tidying milestone.

**Comment by hangler** [comment]
This should be in the latest deployment.

**Comment by karmour** [comment]
Looks good to me! @stephanieyurchak can you confirm one last time?

**Comment by stephanieyurchak** [comment]
Confirmed
