### ISSUE TITLE
Representation table column width

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#133]
> Make first column in table slightly wider so that hovering over a row with a long data label doesn't make the table fidget

**Comment by karmour** [comment]
Confirmed in Edge.

@stephanieyurchak can you test in Chrome?

**Comment by stephanieyurchak** [comment]
@karmour, I'm not seeing any movement in the table when I hover over the rows on this tab in Chrome.

**Comment by hangler** [comment]
👍
