### ISSUE TITLE
Representation default filters

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#134]
> Set default filters on employee type as follows:
> * 2020: All
> * 2018: Regular

**Comment by karmour** [comment]
This appears fixed. @stephanieyurchak can you confirm that for 2020 we only want to allow "All" as the filterable employee type on the Representation tabs?

**Comment by stephanieyurchak** [comment]
This is working correctly. We only want "All" for 2020 for each ministries other than BCPS which has every Employee Types in the data, and that is working as expected. Similarly for 2018 BCPS has every Employee Type available and defaults to "Regular" when another ministry is selected, as it should.

**Comment by karmour** [comment]
Great, we'll call this closed.
