### ISSUE TITLE
Region table: 2020 tooltips not appearing

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#138]
> 2020 revised/new tooltips not showing up

**Comment by karmour** [comment]
There are now tooltips on the "by Region" sub-tab, but they are defaulting to the 2018 tooltips even with the 2020 dataset. @hangler can you investigate?

**Comment by hangler** [comment]
This should be fixed.

**Comment by karmour** [comment]
Confirmed!
