### ISSUE TITLE
Left-justify header

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#139]
> Left-justify the BC Stats logo and "Workforce Profiles" header so that they look more in line with the filters

**Comment by hangler** [comment]
@karmour The image will always be centred, because the image will always take up 100% of the column width (less the gutters on the sides). So left-justifying the text looks like this. I think it still looks good, what do you think?

<img width="250" alt="Screen Shot 2021-04-07 at 2 43 24 PM" src="https://user-images.githubusercontent.com/3538990/113938559-a1874580-97af-11eb-9568-3b87ae98e88b.png">

**Comment by karmour** [comment]
Yes looks good to me! Thanks :)

**Comment by karmour** [comment]
At normal screen size this appears great. Gets a bit funny when reducing window size (image shrinks while header tries to word wrap). Will create a new ticket for screen size issues.

**Comment by hangler** [comment]
OK, the screen size issue ticket is #148. Closing this one. Thank you!
