### ISSUE TITLE
Change label for Ministry

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#140]
> Change "Ministry" to read "Organization" in the filters and the chart legends

**Comment by hangler** [comment]
@karmour Just to check, are we still OK to have the actual tab named "Ministries"?

**Comment by karmour** [comment]
Good catch - if it's not complicated, let's change that to Organizations too.

**Comment by hangler** [comment]
OK, on **that** note, do we even want to rename `Ministry_Key` in the data to `Organization_Key`, while it's still relatively early on? Tagging in @stephanieyurchak too.

**Comment by karmour** [comment]
Hi Frank, we discussed and it would require some code revisions on our end and a re-upload to DataBC, so we're willing to leave the field (and related csv file) improperly named as Ministry_Key. Thanks for checking!

**Comment by karmour** [comment]
Confirmed.
