### ISSUE TITLE
Tweak 2020 tooltip text for % Available Workforce

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#142]
> * Comparison tab: The Available Workforce shows the representation of designated groups in the BC Workforce. It has been adjusted to represent the types of jobs employed by the BC Public Service within each ministry, region, or occupational group, as applicable. Source: Statistics Canada, 2016 Census and the 2017 Canadian Survey on Disability.
> * Representation tab: The % Available Workforce shows the representation of designated groups in the BC Workforce. It has been adjusted to represent the types of jobs employed by the BC Public Service within each ministry, region, or occupational group, as applicable. Source: Statistics Canada, 2016 Census and the 2017 Canadian Survey on Disability

**Comment by karmour** [comment]
The text edits look good! 

One thing I have just noticed is that the tooltips on the Comparison tab (legend) are in a different place from the Representation tab (table). Would be better if they were handled the same everywhere. Will make a separate ticket for that.

**Comment by stephanieyurchak** [comment]
@karmour The comparison tab has Available workforce in the legend and the table while representation tab just has it in the table. Are you suggesting removing the tool tip from the legend on the comparison tab and only having it in the table? I think it would be better to add one to the table than swap the location of it, thoughts?

**Comment by karmour** [comment]
Yes that's a good solution, @stephanieyurchak. Not sure how to link this ticket to #150 (or maybe I just did?). Will post this suggested solution there too.

**Comment by hangler** [comment]
Now dealt with in #150. We can do any further discussion there as needed.
