### ISSUE TITLE
Tooltips appear in different places on Comparison and Representation tabs

### ISSUE THREAD

**Issue by karmour** [bcgov/workforce-profile-tool#150]
Nice to have - standardize by moving the Comparison tooltips to the table below the visual?

**Comment by hangler** [comment]
Or, should they maybe be in both places...? @karmour @stephanieyurchak what do you think?

**Comment by karmour** [comment]
@stephanieyurchak agrees - so how could I refuse? :-) Let's do that!

**Comment by karmour** [comment]
I don't think these are in the deployed version yet -- the Comparison tooltips only appear on the Legend at present. Will move this to the "Final Tidying" milestone for now.

**Comment by hangler** [comment]
This should be in the latest deployment.

**Comment by karmour** [comment]
I see the tooltips now in both the Legend and on the data table below! The only oddity is that the Shortfall tooltip for 2020 in the Legend on both Representation tabs does not actually show hover text (the one in the tables below does).

**Comment by hangler** [comment]
@karmour Just deployed a fix that might address this issue. I can see the tooltips in Edge on Windows. If this doesn't work, let's try to reproduce tomorrow.

**Comment by karmour** [comment]
Yes that seems to have worked - the Shortfall tooltip text now appears when hovering over the legend. Confirmed in both Edge and Chrome.
