### ISSUE TITLE
Update Representation tab's chart X-axis label to be generic or dynamic

### ISSUE THREAD

**Issue by karmour** [bcgov/workforce-profile-tool#151]
Currently says "Count in BCPS" -- either update to be a static "Count in Organization", or (nice to have) dynamic based on Organization filter selection.

**Comment by karmour** [comment]
I don't think this worked - I still see "Count in BCPS" on the X-Axis label regardless of which Organization I'm using in the filter. @hangler can you re-check?

**Comment by hangler** [comment]
Sorry @karmour, it's fixed in the code but not yet deployed. Just about to write you an email on this :-)

**Comment by karmour** [comment]
Confirmed! And thanks for doing the nice-to-have variant. 👍
