### ISSUE TITLE
Disability labels on Representation tab

### ISSUE THREAD

**Issue by karmour** [bcgov/workforce-profile-tool#153]
Can we update the column headers in the Persons With Disabilities table on the Representation tabs (by Occupation, Region)? Currently they use "disabled" and "non-disabled", but we'd like to replace these with "Persons with Disabilities" and "Persons without Disabilities". If this will cause table column width issues, please let us know and we'll come up with a shorter alternative. 

Additionally, can we add "(PWD)" at the end of the table heading (picture below). Then we can update the rest of the table columns beyond the ones noted above to use "PWD" instead of "disabled" (e.g., Rate of PWD, Shortfall of PWD, etc.).

![image](https://user-images.githubusercontent.com/5818030/114756957-20c8cc00-9d10-11eb-8023-76fbf05e288f.png)

Thank you!

**Comment by hangler** [comment]
@karmour The column headers do get very long if we expand the text. Could we come up with a shorter version? And/or just use "PWD" everywhere?

**Comment by karmour** [comment]
Hi Frank, yes then let's use "PWD" and "non-PWD" for those two columns, since we'll have the full wording and acronym in the header above the table anyway. Thank you!

**Comment by karmour** [comment]
The table headers look good, but the sub-heading above the table doesn't include the acronym yet. Can you update the sub-heading above the table to be "Persons with Disabilities (PWD)"?

![image](https://user-images.githubusercontent.com/5818030/115311229-26654e00-a124-11eb-8921-3e1c8a19d710.png)
