### ISSUE TITLE
Data dictionary for CSVs

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#74]
Outline the data files the app currently uses, what the columns are, etc.

**Comment by hangler** [comment]
@karmour Would Kate already have something like this?

**Comment by karmour** [comment]
@hangler Sounds like there's no existing data dictionary to leverage, so we would greatly appreciate you taking a first crack at this to help Stephanie familiarize herself with the dashboard's data needs!

**Comment by hangler** [comment]
OK, will take a look!

**Comment by hangler** [comment]
Working on it here: https://github.com/bcgov/workforce-profile-tool/wiki/Data-Dictionary

**Comment by hangler** [comment]
Complete.
