### ISSUE TITLE
Remove data files from repository

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#77]
@karmour to advise whether we need to remove from repository history as well.

**Comment by karmour** [comment]
Robin has confirmed that there's no auto-deployment in place, so we should be OK to delete the files without impact to the live state. I've also discussed internally and we think it's sufficient to delete the existing files from the folder and not worry about the repository history -- they are non-sensitive data files after all.

@hangler -- any other considerations before we delete them? Will this affect your data dictionary?

**Comment by hangler** [comment]
It would not affect the data dictionary, except I would remove the links to the actual data files. I assume I can still provide ~10 lines of data as an example?

**Comment by karmour** [comment]
I think that should be fine.

**Comment by karmour** [comment]
@hangler - let me know when you've finished with the data examples, and I'll go ahead and remove the files. Thanks!

**Comment by hangler** [comment]
Hi @karmour — I can just do it now, no problem. I have the files locally still. Pushing the change will automatically close this ticket.
