### ISSUE TITLE
Change link to WFP info page

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#93]
Should be: https://www2.gov.bc.ca/gov/content/data/statistics/government/employee-research/workforce-profiles

**Comment by karmour** [comment]
Just to confirm - I want to update the URL mentioned on the landing page that directs people to our WFP information page on our website -- I don't want to change the URL of the tool itself. :-)

**Comment by hangler** [comment]
Ah that is a good clarification indeed 😄 Sorry, will change that.
