### ISSUE TITLE
Update wording on landing page

### ISSUE THREAD

**Issue by hangler** [bcgov/workforce-profile-tool#94]
Kyle to provide:

> Update wording - include new caveats >> placeholders for now
> * Default views to All
> * PWD mismatch with federal
> * Others?
>     * 2018 favours REG data - make this clear to users
> * Does using SBC as point of contact still make sense?

**Comment by karmour** [comment]
Let's update the Contact blurb to say: "Please contact BC Stats [mailto:work.environment.survey@gov.bc.ca] if you experience any technical difficulties or have any questions about the content of this app."

Still working on the rest of the landing page content. :-)

**Comment by hangler** [comment]
All done.

**Comment by karmour** [comment]
Crikeys, I forgot a caveat... :( Sorry about that! Can we add one more and position it as the fourth caveat (i.e., before the final caveat about Hiring/Flow)? The text would be as follows:
		
Note: Statistics Canada and BC Stats use different methods to identify Persons with Disabilities. BC Stats currently uses a definition from the UN Convention on the Rights of Persons with Disabilities, focusing on those with long-term impairments that interact with barriers. Statistics Canada uses a series of census and other survey questions to identify Persons with Disabilities, which may encompass a wider portion of the population. Please use caution when comparing the rates of Persons with Disabilities in the BC Public Service (calculated by BC Stats) against the available workforce and population of BC (calculated by Statistics Canada).

**Comment by karmour** [comment]
Hi Frank, yes then let's use "PWD" and "non-PWD" for those two columns, since we'll have the full wording and acronym in the header above the table anyway. Thank you!

**Comment by karmour** [comment]
Apologies, could we add "(pwd)" after the first mention of "Persons with Disabilities" in the extra caveat above? Since we will be using it as a shortened acronym in one of the tabs, it makes sense to reference it here too.

Additionally, it looks like we'll need yet another caveat, but it's presently undergoing a hasty review and approval by the client (very, very sorry). I can paste the text here the minute it's approved.

**Comment by hangler** [comment]
Yup, no problem, will wait on your update to adjust the text.

**Comment by karmour** [comment]
I now have confirmation on the wording for the final caveat: "Note that while BC Stats collects employee information on LGBTQ2S+ identity, as well as on non-binary gender identities, the Workforce Profiles do not presently include this information as no federal data on BC Population or Available Workforce exists for comparison. At this time, the tool includes both cis and trans women in the Women category."

Can this be placed in between the "Some tabs make comparisons..." and "Note: Statistics Canada..." paragraphs?

Thanks for your patience!

**Comment by karmour** [comment]
Thanks, this looks good (and long!).

**Comment by karmour** [comment]
Revision to the second paragraph to make reference to how to use filters on a mobile device:

"You can navigate between sections using the named tabs at the top of this area. You can also refine the visualizations and tables on each tab by employing one or more filters from the available list -- on most screens, these filters will be shown to the left (in blue). For mobile devices, filters instead appear in a hidden menu above the page tabs; click on the "Show variables" button to display them, or the "Hide variables" button to minimize them again. Note that not all filters are available to be used on every tab."

**Comment by hangler** [comment]
Done and deployed.

**Comment by karmour** [comment]
Thank you!
